services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.coolify
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      # SQLite database persistence
      - database_data:/var/www/html/database
      # Laravel storage persistence
      - storage_data:/var/www/html/storage
      # Bootstrap cache persistence
      - bootstrap_cache:/var/www/html/bootstrap/cache
    environment:
      # Basic Laravel configuration
      APP_NAME: "PHP Sign"
      APP_ENV: production
      APP_DEBUG: false
      APP_URL: "${APP_URL:-http://localhost}"
      
      # Database configuration for SQLite
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
      
      # Cache and session configuration
      CACHE_DRIVER: file
      SESSION_DRIVER: file
      QUEUE_CONNECTION: sync
      
      # Mail configuration (customize as needed)
      MAIL_MAILER: smtp
      MAIL_HOST: "${MAIL_HOST:-localhost}"
      MAIL_PORT: "${MAIL_PORT:-587}"
      MAIL_USERNAME: "${MAIL_USERNAME}"
      MAIL_PASSWORD: "${MAIL_PASSWORD}"
      MAIL_ENCRYPTION: "${MAIL_ENCRYPTION:-tls}"
      MAIL_FROM_ADDRESS: "${MAIL_FROM_ADDRESS:-noreply@example.com}"
      MAIL_FROM_NAME: "${APP_NAME}"
      
      # Security
      APP_KEY: "${APP_KEY}"
      
      # Optional: Telescope (disable in production if not needed)
      TELESCOPE_ENABLED: false
    ports:
      - "9000:9000"
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "php", "-v"]
      timeout: 3s
      retries: 3
      start_period: 30s

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    ports:
      - "${PORT:-80}:80"
    volumes:
      - ./public:/var/www/html/public:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      app:
        condition: service_healthy
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      timeout: 3s
      retries: 3
      start_period: 30s

volumes:
  database_data:
    driver: local
  storage_data:
    driver: local
  bootstrap_cache:
    driver: local

networks:
  app_network:
    driver: bridge 