services:
    mysql:
        image: mysql:9.0.1
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mydb
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
            - ./backup:/backup
